services:
  php:
    container_name: api-php
    image: ${IMAGES_PREFIX:-}app-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php_dev # Change to php_prod for production
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-qwerty}@database:3306/${MYSQL_DATABASE:-db}?serverVersion=${MYSQL_VERSION:-8}&charset=utf8mb4
    volumes:
      - ./:/app:rw
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: api-frontend
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./:/app:rw
    command: sh -c "if [ ! -d node_modules ]; then npm install; fi; npm run dev -- --host"
    environment:
      NODE_ENV: development

  nginx:
    container_name: api-nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./:/app:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - frontend

  database:
    container_name: api-database
    image: mysql:${MYSQL_VERSION:-8}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-qwerty}
      MYSQL_USER: ${MYSQL_USER:-symfony}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:

networks:
  default:
    name: symfony_network
